export const COACHING_PRICE_LIST = [
    {
        'service': 'Career Coaching',
        'price': '$89',
        'priceInfo': 'One 30 min call',
        'detail': 'Connect with one of our career experts who can answer your questions, offer guidance, and help you get your job search on the right track.',
        'imgSrc': 'https://www.flexjobs.com/images/img-coaching.jpg',
        'imgInfo': 'Career Coaching photo',
        'moreHref': '/career-coaching',
    },
    {
        'service': 'Resume Review',
        'price': '$179',
        'priceInfo': 'One review & update',
        'detail': 'A FlexJobs career coach will take your existing resume and renovate it to ensure it is as effective as it can be!',
        'imgSrc': 'https://www.flexjobs.com/images/img-resume.jpg',
        'imgInfo': 'Resume Review photo',
        'moreHref': '/resume-review',
    },
    {
        'service': 'Career Coaching & Resume Review Bundle',
        'price': '$239',
        'priceInfo': 'One 30 min call &<br/> one resume review',
        'detail': 'Connect with a FlexJobs career coach one-on-one and receive a professional resume review and revision.',
        'imgSrc': 'https://www.flexjobs.com/images/img-bundle-horiz.jpg',
        'imgInfo': 'Career Coaching & Resume Review Bundle photo',
        'moreHref': '/career-coaching-resume-review-bundle',
    },
    {
        'service': 'Career Change Coaching',
        'price': '$149',
        'priceInfo': 'One career change self-assessment tool and one 30-minute call',
        'detail': 'Two combined services to empower your career transition: a comprehensive self-assessment to clarify your career options and one-on-one action planning with your coach.',
        'imgClass': 'career-change-col',
        'moreHref': '/career-change-coaching',
    },
    {
        'service': 'Mock Interviews',
        'price': '$89',
        'priceInfo': 'One 30 min mock interview',
        'detail': 'Partner with a FlexJobs career expert to practice your interviewing skills, gain confidence, calm your nerves and learn how to be as effective as possible during job interviews!',
        'imgClass': 'mock-col',
        'imgSrc': 'https://www.flexjobs.com/images/img-mock.jpg',        
        'moreHref': '/mock-job-interview',
    },
]